### ISSUE TITLE
Buttons not responding after a while on HA 2021.6

### ISSUE THREAD

**Issue by maxgiordan** [jcwillox/lovelace-paper-buttons-row#48] opened 2021-06-06 11:06 UTC
Hi, there seems to be a problem with the latest version of Home Assistant 2021.6.
Browsers are no longer responsive with tap_action unless you reload them.
Clearing the cache is useless.
The problem appears to be lirc.
Thanks in advance if you want and you can update your splendid work! 👍

**Comment by jcwillox** [comment] 2021-06-06 13:52
Thanks, I think I had that happen to me too, but after refreshing, everything worked again, and I haven't had the problem since, do have any steps to reproduce this bug?

**Comment by maxgiordan** [comment] 2021-06-06 18:26
In fact I can't figure out if it's a button-row bug or something else.
I'll give an example with Chrome on a pc:
in the home assistant main page I activate the toggle on a lamp and everything works (your job is really too good) but the page freezes, or rather, only the buttons and only the toggle. Instead the change of state works even if the main page is in freeze.
In the other tabs everything works fine.
To regain control of the main page buttons I have to update chrome.
I do not understand...

**Comment by jcwillox** [comment] 2021-06-09 02:05
Yep, I've had it happen again twice, it seems to only happen on windows that are left open for a while, which may indicate that it's got something to do with Home Assistant closing the connection to the server. More interestingly, buttons that don't have a state, i.e. don't listen for state updates, continue to work, so my guess is that there's something wrong with my state/templating logic that I'll have to look into.

**Comment by maxgiordan** [comment] 2021-06-09 07:17
Yes, that's right, only that to me the state of the buttons changes regularly ... what doesn't work is the tap_action that goes to freeze after the first push and resumes only with a refresh.  
Thanks for what you do, really!

**Comment by jcwillox** [comment] 2021-06-26 12:53
I've narrowed down the issue, this may be a little technical, but I thought I'd mention my findings here anyway. The buttons are not receiving events from the action handler, and it seems that's because when you tap the button and it changes state, the reference the action handler holds for that button is lost, as the button is effectively being removed and recreated. Rebinding the button to the action handler works, but only for one action before the button reference is invalidated again.

I have no idea why this is only happing sometimes, and other times the buttons are updated correctly and the reference remains intact. It should at least be consistent? I'll probably create a temporary (kinda bad) fix for this soon unless I manage to figure out the root cause.

**Comment by maxgiordan** [comment] 2021-06-26 13:22
I fully agree with your statements: all correct!  
I can't understand why now, from my dashboard everything works perfectly while from the app the buttons only work once.  
Interesting problem ...thanks so much 😀

**Comment by lfrlucas** [comment] 2021-07-04 15:17
Hi, I'm experiencing the exactly the same issue. Some times the buttons do not react on my wall tablet but work on other devices. Refreshing usually solves.

**Comment by jcwillox** [comment] 2021-07-05 14:17
I'll release a patch which hopefully fixes this tomorrow

**Comment by jcwillox** [comment] 2021-07-06 08:06
Release [0.6.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.6.0) should hopefully fix this issue, let me know if you still have the issue when running the new version.

**Comment by maxgiordan** [comment] 2021-07-06 18:02
> Release [0.6.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/0.6.0) should hopefully fix this issue, let me know if you still have the issue when running the new version.

Hi jcwillox, you are great. It goes great! 
It would be nice to understand the problem ... thank you very much: yours is one of the most beautiful jobs ever for HA!

**Comment by lfrlucas** [comment] 2021-07-06 19:17
The issue is not occurring anymore here. Thanks a lot for the fast fix! It was really annoying and I was actually already searching for alternative cards. Good it is solved. Thanks again.

**Closed** 2021-12-26 14:44 UTC
Labels: bug
