### ISSUE TITLE
Need Help setting icon color to actual light color

### ISSUE THREAD

**Issue by Aldopez** [jcwillox/lovelace-paper-buttons-row#100] opened 2022-08-01 16:13 UTC
Is there any way to set the icon color to the light color currently set for rgb components?

**Comment by jcwillox** [comment] 2022-12-13 13:26
There is now, its actually the default, see release [2.0.0](https://github.com/jcwillox/lovelace-paper-buttons-row/releases/tag/2.0.0) 🎉.

Duplicate of #46

**Closed by jcwillox** 2022-12-13 13:26 UTC
